backend:
  name: git-gateway
  branch: main
  squash_merges: true

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

# media_library:
#   name: A Media Library
#   config:
#     maxFileSize: 500000

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/_index.md"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
      - name: "contact"
        label: "Contact Page"
        file: "content/contact.md"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
      - name: "about"
        label: "About Page"
        file: "content/about.md"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
  - name: "releases" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Release" # Used in the UI, ie.: "New Post"
    folder: "content/releases" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Series", name: "series", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Series", name: "series", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }